@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.lib.command.internal;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;