# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.debug=false

# Environment Properties
minecraft_version=26.1-snapshot-1
minecraft_version_range=[26.1-snapshot-1,)
neo_version=26.1.0.0-alpha.3+snapshot-1
neo_version_range=[26.1.0.0-alpha.1,)
loader_version_range=[5,)

## Mod Properties
mod_id=silentlib
mod_name=Silent Lib
mod_license=MIT
mod_version=12.0.0
release_type = alpha
mod_group_id=net.silentchaos512
mod_authors=SilentChaos512
mod_description=Shared library for SilentChaos512's mods
repo_name=silent-lib
issue_tracker_url=https://github.com/SilentChaos512/SilentLib/issues
display_url=https://github.com/SilentChaos512/SilentLib/blob/26.1.x/README.md

## Curseforge
cf_project_id = 242998
cf_changelog_filename = CHANGELOG.md

## Modrinth
mr_project_id=silent-lib