@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.lib.guidebook;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;