@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.lib.collection;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;