@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.lib.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;